using Test
using NanoporeMultiEventalign

@testset "dtw.jl" begin
    @testset "dtw" begin
        @test dtw(true)
        @test !dtw(false)
    end
end

@testset "persistence.jl" begin
    @testset "loadReference" begin
        @test convert(String,loadReference("sample_data/reference.fa")) == "GAATACAAGCTACTTGTTCTTTTTGCAGGATCCCATCGATTCGAATTCAAGGCCTCTCGAGCCTCTAGAACTATAGTGAGTCGTATTACGTAGATCCAGACATGATAAGATACATTGATGAGTTTGGACAAACCACAACTAGAATGCAGTGAAAAAAATGCTTTATTTGTGAAATTTGTGATGCTATTGCTTTATTTGTAACCATTATAAGCTGCAATAAACAAGTTAACAACAACAATTGCATTCATTTTATGTTTCAGGTTCAGGGGGAGGTGTGGGAGGTTTTTTAATTCGCAAAAAAAAAAGGGAGAGCGACGAGAAGAAGAGGCTTGTATGGACGATGTCTTCCACAACAGAAGACATCGTCCATACAAGCAAAAAA"
    end
end
