name = "NanoporeMultiEventalign"
uuid = "c438b98d-67fd-45c3-9996-84dfdeb636ca"
authors = ["JokingHero <kornellabun@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
